kalabash_webmail/urls.py
# coding: utf-8
from django.urls import path

from . import views

app_name = 'kalabash_webmail'

urlpatterns = [
    path('', views.index, name="index"),
    path('submailboxes', views.submailboxes, name="submailboxes_get"),
    path('getmailcontent', views.getmailcontent, name="mailcontent_get"),
    path('getmailsource', views.getmailsource, name="mailsource_get"),
    path('unseenmsgs', views.check_unseen_messages,
         name="unseen_messages_check"),

    path('delete/', views.delete, name="mail_delete"),
    path('move/', views.move, name="mail_move"),
    path('mark/<path:name>/', views.mark, name="mail_mark"),
    path('mark_as_junk/', views.mark_as_junk, name="mail_mark_as_junk"),
    path('mark_as_not_junk/', views.mark_as_not_junk,
         name="mail_mark_as_not_junk"),

    path('newfolder/', views.newfolder, name="folder_add"),
    path('editfolder/', views.editfolder, name="folder_change"),
    path('delfolder/', views.delfolder, name="folder_delete"),
    path('compressfolder/', views.folder_compress, name="folder_compress"),
    path('emptytrash/', views.empty, name="trash_empty"),

    path('attachments/', views.attachments, name="attachment_list"),
    path('delattachment/', views.delattachment, name="attachment_delete"),
    path('getattachment/', views.getattachment, name="attachment_get"),
]

kalabash_webmail/forms.py
# coding: utf-8

"""Webmail forms."""

from email.header import Header
from email.mime.image import MIMEImage
import os
import pkg_resources

from six.moves.urllib.parse import urlparse, unquote

import lxml.html

from django import forms
from django.conf import settings
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.core.validators import validate_email
from django.utils.translation import gettext_lazy as _

from ckeditor_uploader.widgets import CKEditorUploadingWidget

from kalabash.lib import email_utils, form_utils
from kalabash.parameters import forms as param_forms

from .lib import (
    ImapEmail, create_mail_attachment, decode_payload
)
from .validators import validate_email_list


def html2plaintext(content):
    """HTML to plain text translation.

    :param content: some HTML content
    """
    if not content:
        return ""
    html = lxml.html.fromstring(content)
    plaintext = ""
    for ch in html.iter():
        p = None
        if ch.text is not None:
            p = ch.text.strip('\r\t\n')
        if ch.tag == "img":
            p = ch.get("alt")
        if p is None:
            continue
        plaintext += p + "\n"
    return plaintext


def make_body_images_inline(body):
    """Looks for images inside the body and make them inline.

    Before sending a message in HTML format, it is necessary to find
    all img tags contained in the body in order to rewrite them. For
    example, icons provided by CKeditor are stored on the server
    filesystem and not accessible from the outside. We must embark
    them as parts of the MIME message if we want recipients to
    display them correctly.

    :param body: the HTML body to parse
    """
    html = lxml.html.fromstring(body)
    parts = []
    for tag in html.iter("img"):
        src = tag.get("src")
        if src is None:
            continue
        o = urlparse(src)
        path = unquote(os.path.join(settings.BASE_DIR, o.path[1:]))
        if not os.path.exists(path):
            continue
        fname = os.path.basename(path)
        cid = "%s@kalabash" % os.path.splitext(fname)[0]
        tag.set("src", "cid:%s" % cid)
        with open(path, "rb") as fp:
            part = MIMEImage(fp.read())
        part["Content-ID"] = "<%s>" % cid
        part.replace_header(
            "Content-Type", '%s; name="%s"' % (part["Content-Type"], fname)
        )
        part["Content-Disposition"] = "inline"
        parts.append(part)
    return lxml.html.tostring(html, encoding="unicode"), parts


class ComposeMailForm(forms.Form):
    """Compose mail form."""

    from_ = forms.ChoiceField(
        label=_("From"), choices=[],
        widget=forms.Select(attrs={"class": "selectize"})
    )
    to = forms.CharField(
        label=_("To"), validators=[validate_email_list])
    cc = forms.CharField(
        label=_("Cc"), required=False, validators=[validate_email_list],
        widget=forms.TextInput(
            attrs={"placeholder": _("Enter one or more addresses."),
                   "class": "selectize-contact"})
    )
    bcc = forms.CharField(
        label=_("Bcc"), required=False, validators=[validate_email_list],
        widget=forms.TextInput(
            attrs={"placeholder": _("Enter one or more addresses."),
                   "class": "selectize-contact"})
    )

    subject = forms.CharField(
        label=_("Subject"),
        max_length=255,
        required=False
    )
    origmsgid = forms.CharField(
        label="", required=False, widget=forms.HiddenInput())
    body = forms.CharField(
        required=False, widget=CKEditorUploadingWidget(
            attrs={"class": "editor form-control"})
    )

    def __init__(self, user, *args, **kwargs):
        """Custom constructor."""
        super(ComposeMailForm, self).__init__(*args, **kwargs)
        from_addresses = [(user.email, user.email)]
        for address in user.mailbox.alias_addresses:
            try:
                validate_email(address)
                from_addresses += [(address, address)]
            except forms.ValidationError:
                pass
        additional_sender_addresses = (
            user.mailbox.senderaddress_set.values_list("address", flat=True))
        from_addresses += [
            (address, address) for address in additional_sender_addresses]
        self.fields["from_"].choices = from_addresses
        self.fields["from_"].initial = user.email
        self.field_widths = {
            "cc": "11",
            "bcc": "11",
            "subject": "11"
        }

    def clean_to(self):
        """Convert to a list."""
        to = self.cleaned_data["to"]
        return email_utils.prepare_addresses(to, "envelope")

    def clean_cc(self):
        """Convert to a list."""
        cc = self.cleaned_data["cc"]
        return email_utils.prepare_addresses(cc, "envelope")

    def clean_bcc(self):
        """Convert to a list."""
        bcc = self.cleaned_data["bcc"]
        return email_utils.prepare_addresses(bcc, "envelope")

    def _html_msg(self, sender, headers):
        """Create a multipart message.

        We attach two alternatives:
        * text/html
        * text/plain
        """
        body = self.cleaned_data["body"]
        if body:
            tbody = html2plaintext(body)
            body, images = make_body_images_inline(body)
        else:
            tbody = ""
            images = []
        msg = EmailMultiAlternatives(
            self.cleaned_data["subject"],
            tbody,
            sender, self.cleaned_data["to"],
            cc=self.cleaned_data["cc"],
            bcc=self.cleaned_data["bcc"],
            headers=headers
        )
        msg.attach_alternative(body, "text/html")
        for img in images:
            msg.attach(img)
        return msg

    def _plain_msg(self, sender, headers):
        """Create a simple text message."""
        msg = EmailMessage(
            self.cleaned_data["subject"],
            self.cleaned_data["body"],
            sender,
            self.cleaned_data["to"],
            cc=self.cleaned_data["cc"],
            bcc=self.cleaned_data["bcc"],
            headers=headers
        )
        return msg

    def _format_sender_address(self, user, address):
        """Format address before message is sent."""
        if user.first_name != "" or user.last_name != "":
            return '"{}" <{}>'.format(
                Header(user.fullname, "utf8"), address)
        return address

    def _build_msg(self, request):
        """Build message to send.

        Can be overidden by children.
        """
        headers = {
            "User-Agent": "Kalabash {}".format(
                pkg_resources.get_distribution("kalabash").version)
        }
        origmsgid = self.cleaned_data.get("origmsgid")
        if origmsgid:
            headers.update({
                "References": origmsgid,
                "In-Reply-To": origmsgid
            })
        mode = request.user.parameters.get_value("editor")
        sender = self._format_sender_address(
            request.user, self.cleaned_data["from_"])
        return getattr(self, "_{}_msg".format(mode))(sender, headers)

    def to_msg(self, request):
        """Convert form's content to an object ready to send."""
        msg = self._build_msg(request)
        if request.session["compose_mail"]["attachments"]:
            for attdef in request.session["compose_mail"]["attachments"]:
                msg.attach(create_mail_attachment(attdef))
        return msg


class ForwardMailForm(ComposeMailForm):
    """Forward mail form."""

    def _build_msg(self, request):
        """Convert form's content to a MIME message.

        We also add original attachments (if any) to the new message.
        """
        mbox = request.GET.get("mbox", None)
        mailid = request.GET.get("mailid", None)
        msg = super(ForwardMailForm, self)._build_msg(request)
        origmsg = ImapEmail(request, "%s:%s" % (mbox, mailid))
        if origmsg.attachments:
            for attpart, fname in origmsg.attachments.items():
                attdef, payload = origmsg.fetch_attachment(attpart)
                attdef["fname"] = fname
                msg.attach(create_mail_attachment(
                    attdef, decode_payload(attdef["encoding"], payload)
                ))
        return msg


class FolderForm(forms.Form):
    oldname = forms.CharField(
        label="",
        widget=forms.HiddenInput(attrs={"class": "form-control"}),
        required=False
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}))


class AttachmentForm(forms.Form):
    attachment = forms.FileField(label=_("Select a file"), allow_empty_file=True)


class ParametersForm(param_forms.AdminParametersForm):
    app = "kalabash_webmail"

    sep3 = form_utils.SeparatorField(label=_("General"))

    max_attachment_size = forms.CharField(
        label=_("Maximum attachment size"),
        initial="2048",
        help_text=_(
            "Maximum attachment size in bytes (or KB, MB, GB if specified)")
    )

    sep1 = form_utils.SeparatorField(label=_("IMAP settings"))

    imap_server = forms.CharField(
        label=_("Server address"),
        initial="127.0.0.1",
        help_text=_("Address of your IMAP server")
    )

    imap_secured = form_utils.YesNoField(
        label=_("Use a secured connection"),
        initial=False,
        help_text=_("Use a secured connection to access IMAP server")
    )

    imap_port = forms.IntegerField(
        label=_("Server port"),
        initial=143,
        help_text=_("Listening port of your IMAP server")
    )

    sep2 = form_utils.SeparatorField(label=_("SMTP settings"))

    smtp_server = forms.CharField(
        label=_("Server address"),
        initial="127.0.0.1",
        help_text=_("Address of your SMTP server")
    )

    smtp_secured_mode = forms.ChoiceField(
        label=_("Secured connection mode"),

kalabash_webmail/templates/kalabash_webmail/attachments.html
{% extends "common/generic_modal_form.html" %}
{% load i18n %}
{% load static %}
{% block modalbody %}
{{ block.super }}

<div class="col-sm-12 text-center">
  <input type="button" class="btn btn-primary" id="submit" name="submit" value="{% trans 'Attach' %}" />
</div>

<div id="upload_status" style="display:none">
  <img src="{% static 'css/spinner.gif' %}" /> {% trans "Uploading.." %}
</div>
<iframe id="upload_target" name="upload_target" src="#" 
        style="width:0;height:0;border:0px solid #fff;"></iframe>
<div class="well" id="attachment_list">
  {% for att in attachments %}
  <div class="row">
    <div class="col-sm-12">
      <a href="{% url 'kalabash_webmail:attachment_delete' %}?name={{ att.tmpname }}"
         name="delattachment">
        <span class="fa fa-remove"></span>
      </a>
      <label>{{ att.fname }}</label>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

kalabash_webmail/templates/kalabash_webmail/compose.html
{% load i18n form_tags %}

<form class="form-horizontal" method="POST" action="{{ posturl }}" id="composemail">
  {% csrf_token %}
  {{ form.origmsgid }}
  <div id="compose-container">
    <div id="mailheader">
      {% render_field form.from_ label_width="col-sm-1" %}
      <div class="form-group{% if form.errors.to %} has-error{% endif %}">
	{# handling to field #} 
        <label class="col-sm-1 control-label" for="id_to">{% trans "To" %}</label>
        <div class="col-sm-8">
          <input id="id_to" name="to" class="form-control selectize-contact"
                 value='{% if form.to.value %}{{ form.to.value }}{% endif %}'
                 placeholder="{% trans "Enter one or more addresses." %}">
	  {% if form.to.errors %}
	  {% for error in form.to.errors %}
	  <p class="help-block">{{ error }}</p>
	  {% endfor %}
	  {% endif %}
        </div>

	{# handling cc and bcc buttons #}
        {% if not form.cc.value or not form.bcc.value %}
        <div class="col-sm-2">
	  {% if not form.cc.value %}
          <button id="add_cc" class="btn btn-default btn-xs">
	    <span class="fa fa-plus"></span> {% trans "Cc" %}
	  </button>
	  {% endif %}
	  {% if not form.bcc.value %}
          <button id="add_bcc" class="btn btn-default btn-xs">
	    <span class="fa fa-plus"> {% trans "Bcc" %}</span>
	  </button>
	  {% endif %}
        </div>
       {% endif %}
      </div>

      {# display cc field when required #}
      {% if form.cc.value %}
        {% render_field form.cc label_width="col-sm-1" %}
      {% else %}
        {% render_field form.cc label_width="col-sm-1" hidden=True %}
      {% endif %}

      {# display bcc field when required #}
      {% if form.bcc.value %}
        {% render_field form.bcc label_width="col-sm-1" %}
      {% else %}
        {% render_field form.bcc label_width="col-sm-1" hidden=True %}
      {% endif %}

      {% render_field form.subject label_width="col-sm-1" %}

    </div>

    <div id="body_container">
      {{ form.body }}
    </div>

  </div>
</form>

kalabash_webmail/templates/kalabash_webmail/compose_menubar.html
{% extends "common/buttons_list.html" %}

{% load i18n %}

{% block extra_buttons %}
<div class="nav navbar-nav action-buttons btn-group">
  <a name="attachments" href="{% url 'kalabash_webmail:attachment_list' %}" class="btn btn-default">
    <span class="fa fa-paperclip"></span>
    {% trans "Attachments" %}
    <span id="attachment_counter">{% if attachment_counter %}({{ attachment_counter }}){% endif %}</span>
  </a>
</div>
{% endblock %}

kalabash_webmail/templates/kalabash_webmail/email_list.html
{% load i18n %}
{% load webmail_tags %}
{% load static %}

{% if with_top_div %}<div id="emails">{% endif %}
  {% for email in email_list %}
  <div id="{{ email.imapid }}" class="row email{% if email.style %} {{ email.style }}{% endif %}" data-page="{{ page }}">
    <div class="hidden-xs col-sm-1">
      <img name="drag" src="{% static 'pics/grippy.png' %}" class="draggable" />
      <input type="checkbox" />
      <span class="flag fa fa-lg {% if email.flagged %}fa-star{% else %}fa-star-o{% endif %}"></span>
    </div>
    <div class="col-xs-9 col-sm-9 openable">
      {{ email.subject|parse_imap_header:"subject"|truncatechars:60 }}
      <p class="text-muted">
        {{ email.from|parse_imap_header:"from" }}
      </p>
    </div>
    <div class="col-xs-3 col-sm-2 text-right">
      {{ email.date|parse_imap_header:"date" }}
      <p>{% if email.answered %}<span class="fa fa-mail-reply"></span>{% endif %}{% if email.forwarded %} <span class="fa fa-mail-forward"></span>{% endif %}{% if email.attachments %} <span class="fa fa-paperclip"></span>{% endif %} <span class="text-muted">{{ email.size|filesizeformat }}</span></p>
    </div>
  </div>
  {% endfor %}
{% if with_top_div %}</div>{% endif %}

kalabash_webmail/templates/kalabash_webmail/folder.html
{% extends "common/generic_modal_form.html" %}
{% load i18n webmail_tags %}
{% block extrafields %}
<div id="folders2" class="well">
  <ul class="nav nav-pills nav-stacked">
    <li class="nav-header">{% trans "Parent mailbox" %}</li>
    {% print_mailboxes mboxes selected withunseen selectonly hdelimiter %}
  </ul>
</div>
{% endblock %}

kalabash_webmail/templates/kalabash_webmail/folders.html
{% load i18n webmail_tags %}
<ul class="nav nav-sidebar">
  {% print_mailboxes mboxes selected withunseen %}
</ul>

kalabash_webmail/templates/kalabash_webmail/headers.html
{% load i18n lib_tags webmail_tags %}

<table id="emailheaders" class="table table-condensed">
  {% for hdr in headers %}
    <tr>
      <th>{{ hdr.name|localize_header_name }}</th>
      <td>
        {% if hdr.safe %}
           {% if hdr.value|length > 100 %}
              {{ hdr.value|safe|truncatechars_html:100 }}
           {% else %}
              {{ hdr.value|safe }}
           {% endif %}
      {% elif hdr.value|length > 100 %}
          {{ hdr.value|truncatechars_html:100}}
      {% else %}
          {{ hdr.value}}
      {% endif %}</td>
    </tr>
  {% endfor %}
  {% if attachments %}
    <tr>
      <th>{% trans "Attachments" %}</th>
      <td>
        {% for key, fname in attachments.items %}
          <a href="{% attachment_url mbox mailid fname key %}">{{ fname }}</a>
        {% endfor %}
      </td>
    </tr>
  {% endif %}
</table>

<iframe src="{% url 'kalabash_webmail:mailcontent_get' %}?mbox={{ mbox }}&mailid={{ mailid }}&links={{ links }}" id="mailcontent"></iframe>

kalabash_webmail/templates/kalabash_webmail/index.html
{% extends "twocols.html" %}{% load i18n lib_tags webmail_tags %}
{% load static %}
{% block pagetitle %}Webmail{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'jquery-ui/themes/base/all.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'kalabash_webmail/css/webmail.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.htmltable.js' %}"></script>
<script type="text/javascript" src="{% static 'js/searchbar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.infinitescroll.js' %}"></script>
<script type="text/javascript" src="{% static 'kalabash_webmail/js/webmail.js' %}"></script>
<script type="text/javascript">
var webmail = undefined;

$(document).ready(function() {
    webmail = new Webmail({
        poller_interval: {{ refreshrate }},
        poller_url: "{% url 'kalabash_webmail:unseen_messages_check' %}",
        listing_url: "{% url 'kalabash_webmail:index' %}?action=listmailbox",
        move_url: "{% url 'kalabash_webmail:mail_move' %}",
        submboxes_url: "{% url 'kalabash_webmail:submailboxes_get' %}",
        delattachment_url: "{% url 'kalabash_webmail:attachment_delete' %}",
        contactListUrl: {% if contacts_plugin_enabled %}"{% url 'api:emailaddress-list' %}"{% else %}null{% endif %},
        deflocation: "{{ deflocation }}",
        defcallback: "{{ defcallback }}",
        ro_mboxes: {% tolist ro_mboxes %},
        trash: "{{ trash }}",
        hdelimiter: '{{ hdelimiter }}',
        mboxes_col_width: {{ mboxes_col_width }}
    });
});
</script>
{% endblock %}

{% block leftcol %}
<div class="leftcol-heading text-center">
  <a name="compose" class="btn btn-success btn-lg" href="compose">
    <span class="fa fa-edit"></span>
    {% trans "Compose" %}
  </a>
</div>

<div id="folders">
  {{ mboxes }}
</div>

<div id="left-toolbar" class="row">
  <div class="col-sm-2">
    <div id="mboxactions" class="btn-group dropup">
      <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
        <span class="fa fa-cog"></span>
      </button>
      {% mboxes_menu %}
    </div>
  </div>
  {% if quota != -1 %}
  <div id="quotabox" class="col-sm-10">
    <div id="quotabar" class="progress">
      <div class="progress-bar {% progress_color quota %}" role="progressbar" style="width: {{ quota }}%" aria-valuenow="{{ quota }}" aria-valuemin="0" aria-valuemax="100">{{ quota }}%</div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

{% block apparea %}
<div id="menubar" role="navbar"></div>
<div id="listing"></div>

{% endblock %}

kalabash_webmail/templates/kalabash_webmail/mail_source.html
{% extends "common/generic_modal.html" %}

{% block modal_css_classes %}modal-lg{% endblock %}

{% block modalbody %}
<pre>
{{ source }}
</pre>
{% endblock %}

kalabash_webmail/templates/kalabash_webmail/main_action_bar.html
{% extends "common/buttons_list.html" %}

{% load i18n %}

{% block before_menubar %}
  <div class="col-xs-5" style="display: flex">
    <input
        class="hidden-xs"
        type="checkbox" id="selectAll" name="selectAll" style="margin-right: 10px"
        title="{% translate "Toggle selection" %}"
    />
    <div style="flex: 1">
      {% include "common/email_searchbar.html" with extraopts=extraopts %}
    </div>
  </div>
{% endblock %}

{% block menubar_classes %}col-xs-7{% endblock %}

kalabash_webmail/templates/kalabash_webmail/upload_done.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://www.w3.org/2005/10/profile">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="text/javascript">
    {% if status == "ok" %}
    parent.webmail.upload_success("{{ fname }}", "{{ tmpname }}");
    {% else %}
    parent.webmail.upload_error("{{ error }}");
    {% endif %}
  </script>
</head>
<body></body>
</html>